/* Auto-generated by genmsg_cpp for file /home/robo/DD2425_2013/fuerte_workspace/camera/msg/Position.msg */
#ifndef CAMERA_MESSAGE_POSITION_H
#define CAMERA_MESSAGE_POSITION_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace camera
{
template <class ContainerAllocator>
struct Position_ {
  typedef Position_<ContainerAllocator> Type;

  Position_()
  : x(0)
  , depth(0)
  {
  }

  Position_(const ContainerAllocator& _alloc)
  : x(0)
  , depth(0)
  {
  }

  typedef int32_t _x_type;
  int32_t x;

  typedef int32_t _depth_type;
  int32_t depth;


  typedef boost::shared_ptr< ::camera::Position_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::camera::Position_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct Position
typedef  ::camera::Position_<std::allocator<void> > Position;

typedef boost::shared_ptr< ::camera::Position> PositionPtr;
typedef boost::shared_ptr< ::camera::Position const> PositionConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::camera::Position_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::camera::Position_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace camera

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::camera::Position_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::camera::Position_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::camera::Position_<ContainerAllocator> > {
  static const char* value() 
  {
    return "19be51867ea54121b0358052b3ed7d11";
  }

  static const char* value(const  ::camera::Position_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x19be51867ea54121ULL;
  static const uint64_t static_value2 = 0xb0358052b3ed7d11ULL;
};

template<class ContainerAllocator>
struct DataType< ::camera::Position_<ContainerAllocator> > {
  static const char* value() 
  {
    return "camera/Position";
  }

  static const char* value(const  ::camera::Position_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::camera::Position_<ContainerAllocator> > {
  static const char* value() 
  {
    return "int32 x\n\
int32 depth\n\
\n\
";
  }

  static const char* value(const  ::camera::Position_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::camera::Position_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::camera::Position_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.x);
    stream.next(m.depth);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct Position_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::camera::Position_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::camera::Position_<ContainerAllocator> & v) 
  {
    s << indent << "x: ";
    Printer<int32_t>::stream(s, indent + "  ", v.x);
    s << indent << "depth: ";
    Printer<int32_t>::stream(s, indent + "  ", v.depth);
  }
};


} // namespace message_operations
} // namespace ros

#endif // CAMERA_MESSAGE_POSITION_H

