/* Auto-generated by genmsg_cpp for file /home/robo/DD2425_2013/fuerte_workspace/robotics_g7/robot/msg/Rotate.msg */
#ifndef ROBOT_MESSAGE_ROTATE_H
#define ROBOT_MESSAGE_ROTATE_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace robot
{
template <class ContainerAllocator>
struct Rotate_ {
  typedef Rotate_<ContainerAllocator> Type;

  Rotate_()
  : right(false)
  {
  }

  Rotate_(const ContainerAllocator& _alloc)
  : right(false)
  {
  }

  typedef uint8_t _right_type;
  uint8_t right;


  typedef boost::shared_ptr< ::robot::Rotate_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot::Rotate_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct Rotate
typedef  ::robot::Rotate_<std::allocator<void> > Rotate;

typedef boost::shared_ptr< ::robot::Rotate> RotatePtr;
typedef boost::shared_ptr< ::robot::Rotate const> RotateConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::robot::Rotate_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::robot::Rotate_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace robot

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::robot::Rotate_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::robot::Rotate_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::robot::Rotate_<ContainerAllocator> > {
  static const char* value() 
  {
    return "90337cd7fb14d26b7be15ee3df49f209";
  }

  static const char* value(const  ::robot::Rotate_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x90337cd7fb14d26bULL;
  static const uint64_t static_value2 = 0x7be15ee3df49f209ULL;
};

template<class ContainerAllocator>
struct DataType< ::robot::Rotate_<ContainerAllocator> > {
  static const char* value() 
  {
    return "robot/Rotate";
  }

  static const char* value(const  ::robot::Rotate_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::robot::Rotate_<ContainerAllocator> > {
  static const char* value() 
  {
    return "bool right\n\
\n\
";
  }

  static const char* value(const  ::robot::Rotate_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::robot::Rotate_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::robot::Rotate_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.right);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct Rotate_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot::Rotate_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::robot::Rotate_<ContainerAllocator> & v) 
  {
    s << indent << "right: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.right);
  }
};


} // namespace message_operations
} // namespace ros

#endif // ROBOT_MESSAGE_ROTATE_H

